import Head from 'next/head'
import Link from 'next/link'
import {useEffect} from 'react'
import {useState} from 'react'

export default function Home(initialData) {
  const [formInputs, setFormInputs] = useState()
  const [searchTerm, setSearchTerm] = useState('cats')
  const [searchResults, setSearchResults] = useState([])

    useEffect(()=>{
    setSearchResults(initialData.catGiphys.data)
  }, [initialData])

  const search = async (event) => {
    event.preventDefault()
    let giphys = await fetch(`https://api.giphy.com/v1/gifs/search?q=${formInputs.searchTerm}&api_key=&limit=10`)
    giphys = await giphys.json()
    setSearchResults(giphys.data)
    setSearchTerm(formInputs.searchTerm)
  }

  const handleInputs = (event) => {
    let {name, value} = event.target
    setFormInputs({ ...formInputs, [name]: value });
  }

  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/styles.css" />
      </Head>
      <h1>Giphy Search App</h1>

      <form onSubmit={search}>
        <input name="searchTerm" type="text" onChange={handleInputs} required/>
        <button>Search</button>
      </form>

      <h1>Search results for: {searchTerm}</h1>

      <p>Share this search with others:
        
      <Link
            href="/search/[pid]"
            as={`/search/${searchTerm}`}>
              <a> 
                {`http://localhost:3000/search/${searchTerm}`}
              </a>
      </Link>
     
        </p>

      <div className="giphy-search-results-grid">
      {searchResults.map((each, index) => {
        return(
          <div key={index}>
            <h3>{each.title}</h3>
            <img src={each.images.original.url} alt={each.title}/>
          </div>
        )
      })}
      </div>
    </div>
  )
}

export async function getStaticProps() {
  let catGiphys = await fetch('https://api.giphy.com/v1/gifs/search?q=cats&api_key=&limit=10')
  catGiphys = await catGiphys.json()
  return {props: {catGiphys: catGiphys}}  
}
